# Generated by Django 4.1.3 on 2022-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0002_cliente_nome_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='altura',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(null=True),
        ),
    ]
