# Generated by Django 4.1.3 on 2022-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0004_alter_cliente_nome_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_arquivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
