# Generated by Django 4.1.3 on 2022-12-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0005_alter_cliente_nome_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
    ]
