# Generated by Django 4.1.3 on 2022-12-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0006_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
