# Generated by Django 4.1.3 on 2023-01-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0008_alter_cliente_bairro_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('sobrenome', models.CharField(max_length=200, null=True)),
                ('sexo', models.CharField(max_length=3, null=True)),
                ('altura', models.IntegerField(null=True)),
                ('peso', models.FloatField(null=True)),
                ('nascimento', models.DateField(null=True)),
                ('bairro', models.CharField(max_length=200, null=True)),
                ('cidade', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('nome_arquivo', models.FileField(null=True, upload_to='')),
                ('codigo', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
